### ISSUE TITLE
Cannot use Google CardDAV API

### ISSUE THREAD

**Issue by CGamesPlay** [llldar/tsdav#18]
I'm having a lot of difficulty downloading vCards from the Google contacts API.

```typescript
async function main() {
  const client = new DAVClient({
    serverUrl: "https://www.googleapis.com/",
    credentials: {
      clientId: "...",
      clientSecret: "...",
      tokenUrl: "https://oauth2.googleapis.com/token",
      refreshToken: "...",
    },
    authMethod: "Oauth",
    defaultAccountType: "carddav",
  });

  await client.login();

  const addressBooks = await client.fetchAddressBooks();
  return addressBooks;
}
```

Please note that several of the examples on the README/documentation site contain incorrect information, so I have had to do a fair amount of experimentation to get this far and it's possible I've got one of these URLs configured wrong. In order to get this working at all, I also had to patch the code in [`serviceDiscovery`](https://github.com/llldar/tsdav/blob/e747a0e4c58339e9b4cb2be1bd60a6374a1873ac/src/account.ts#L14) to issue a `PROPFIND` instead of a `GET`, since Google does not respond otherwise. However, the `fetchAddressBooks` method fails regardless, with error `Cannot read property 'supportedReport' of undefined`, originating on [this line](https://github.com/llldar/tsdav/blob/e747a0e4c58339e9b4cb2be1bd60a6374a1873ac/src/collection.ts#L70).

For what it's worth, the following is also in the debug logs (originating from [this line](https://github.com/llldar/tsdav/blob/e747a0e4c58339e9b4cb2be1bd60a6374a1873ac/src/addressBook.ts#L97):

```typescript
  tsdav:addressBook Found address book named Address Book,
  tsdav:addressBook              props: {"displayname":"Address Book","resourcetype":{"collection":{},"addressbook":{}},"getctag":{},"syncToken":{}} +0ms
```

Is this a known issue? Is there a working example of downloading vCards from Google? Thanks!

**Comment by llldar** [comment]
Thanks for reporting the bug, I would investigate and let you know when it's fixed.

**Comment by llldar** [comment]
The issue have been identified and fixed, I will draft a new release this weekend.
