### ISSUE TITLE
broken since 1.1.3 for next

### ISSUE THREAD

**Issue by wzrdtales** [llldar/tsdav#41]
1.1.2 is the last version that works with next

since then it can't find the module

`ModuleNotFoundError: Module not found: Error: Can't resolve 'tsdav'`

**Comment by llldar** [comment]
Can you provide more details?
Like your node js version or browser version,
version of library you are tyring to use it with?

**Comment by zackheil** [comment]
I'm not using next, but I am getting a similar error just trying to use a simple node script. Using node v12, my first line is `const test = require'=('tsdav')` and I get the following:

`Error: Cannot find module '/Users/me/Repositories/caldav-test/node_modules/tsdav/tsdav.cjs.js'. Please verify that the package.json has a valid "main" entry`

**Comment by llldar** [comment]
I'll fix it in next release before Wednesday.

**Comment by wzrdtales** [comment]
sorry when i am busy this is my way of just dropping information :p would have delivered more details now later, but as @zackheil already pointed out, just try to use it in node in whatever way you want.

**Comment by llldar** [comment]
this should be fixed with v1.1.5 now
